language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"

install:
  - pip install .

script:
  - python -m unittest discover -s tests/taxsbp/integration/

notifications:
  email: false
